// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9nHAVrH24_gr1isi6F7lP0L6ZTwTFCec',
    appId: '1:389138215008:web:3731bfd11d0f0fd7f65305',
    messagingSenderId: '389138215008',
    projectId: 'ai-mobileapp-7c28d',
    authDomain: 'ai-mobileapp-7c28d.firebaseapp.com',
    storageBucket: 'ai-mobileapp-7c28d.appspot.com',
    measurementId: 'G-K3NFW0NV12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnh8h5izgtP_4CcH4DzIGfqBZUMC-C7rU',
    appId: '1:389138215008:android:b926b33c58d5d01cf65305',
    messagingSenderId: '389138215008',
    projectId: 'ai-mobileapp-7c28d',
    storageBucket: 'ai-mobileapp-7c28d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2yUN0XkoQqgYQH0SkyI9lZ905s9uOWk',
    appId: '1:389138215008:ios:2965eb326fe4b0c0f65305',
    messagingSenderId: '389138215008',
    projectId: 'ai-mobileapp-7c28d',
    storageBucket: 'ai-mobileapp-7c28d.appspot.com',
    iosBundleId: 'com.example.aiMobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe2yUN0XkoQqgYQH0SkyI9lZ905s9uOWk',
    appId: '1:389138215008:ios:f809552638411c6df65305',
    messagingSenderId: '389138215008',
    projectId: 'ai-mobileapp-7c28d',
    storageBucket: 'ai-mobileapp-7c28d.appspot.com',
    iosBundleId: 'com.example.aiMobileapp.RunnerTests',
  );
}
